### ISSUE TITLE
Consensus Node does not synchronize

### ISSUE THREAD

**Issue by Thisca** [nazar-pc/space-acres#110] opened 2024-02-03 04:41 UTC
The consensus node never moves (Gemini 3h) but it is farming below. Is it ok ? Is there anything I can do to make the consensus node synchronize ?

![Gemini 3h consensus node does not move but it is farming](https://github.com/nazar-pc/space-acres/assets/158676586/08c07c6d-9a53-415c-9b9a-dc30792e8ceb)

**Comment by nazar-pc** [comment] 2024-02-03 04:42
Check the logs, there must be something in there about this

**Comment by Thisca** [comment] 2024-02-03 06:16
I tried to find something but I think I do not have the technical expertise. Can you help me ? logs are below

[space-acres.log](https://github.com/nazar-pc/space-acres/files/14150169/space-acres.log)

**Comment by nazar-pc** [comment] 2024-02-03 06:29
It says zero peers, is it possible that your firewall on Windows blocks application from accessing Internet? Check firewall settings and make sure to allow it.

I see DSN seems to be working, so it is at least partially able to connect, but maybe not fully.

**Comment by Thisca** [comment] 2024-02-03 06:44
I just checked the firewall settings and space-acres is allowed in both public and private networks. Before I updated to the latest version I was using a previous version in 3g, It has never fully synced the consensus node but it would find some peers from time to time and synchronize a bit and than stop. I could see the plotting sector only in the logs before updating to 3h, now space-acres show for the first time plotting and farming on the UI application.

**Comment by nazar-pc** [comment] 2024-02-03 06:57
Can you open PowerShell and try `telnet bootstrap-0.gemini-3h.subspace.network 30333`? It should print like this:
```
Trying 54.82.159.247...
Connected to bootstrap-0.gemini-3h.subspace.network.
Escape character is '^]'.
```

If it is not, please post here what it says.

**Comment by Thisca** [comment] 2024-02-03 15:23
I tried but just a blank dot showed up. It was trying to connect before the blank dot. See pictures below

Picture 1 - typed the command
![Picture 1](https://github.com/nazar-pc/space-acres/assets/158676586/912992f4-05d7-40f5-93b7-384fabb886e1)

Picture 2 - tries to connect
![Picture 2](https://github.com/nazar-pc/space-acres/assets/158676586/b7c009c8-ec92-4c53-9b1f-e96b64dc6b68)

Picture 3 - Blank dot shows up
![Picture 3](https://github.com/nazar-pc/space-acres/assets/158676586/0fa80fcb-3627-4762-859a-9f1a11eca58e)

**Comment by nazar-pc** [comment] 2024-02-03 15:33
Then you have issues connecting to bootstrap node, either local firewall or ISP or country-wide firewall or something else prevents you from connecting to the node.

Tr contacting your ISP about it, there isn't much we can do if there is a wall between your machine and bootstrap nodes for some reason.

**Comment by Thisca** [comment] 2024-02-11 18:48
I made changes in my ISP router and now both port 30333 and 30433 appear open (online check tools). I still cannot have the consensus node to sync however now I have upload and download speeds in my logs (see below). In the logs there is a statement says that the conection was blocked by the software in the host computer giving me the OS error number 10053. I made sure that it was not the firewall setting since I ran space acres with the firewall down. 

When space acres was in the Gemini 3g my node was syncing (finding peers) but was getting super slow when reaching the end of the blockchain. To me it could be that since Gemini 3h has not been released it somehow does not find the peers in time and conection is cut.

Do you think VPN or trying to use proxy servers could solve the problem ?

Based on the logs below, are you sure that nothing can be done on the space acres side to improve the situation ?

[space-acres.log](https://github.com/nazar-pc/space-acres/files/14233333/space-acres.log)

**Comment by nazar-pc** [comment] 2024-02-11 18:54
As I said before, you node has to be able to reach to bootstrap nodes in order to become a part of the network. Port forwarding is helpful, but not sufficient.

I don't think I have a good answer as to why this might happen, you might try to check with telnet from another machine on your local network if you have one or try some port checking tool on the mobile phone, this is to confirm whether the issue is on your local network or that machine specifically.

Unless you see connection via something like telnet and start seeing peers in logs nothing will work.

And do let us know if you find out why this happened so others can learn in the future.

So far I don't think there is anything inherently wrong with Space Acres and will close the issue, but feel free to continue discussion.

**Closed by nazar-pc** 2024-02-11 18:54 UTC
Labels: question
