### ISSUE TITLE
App crash in Windows due to running out of virtual memory

### ISSUE THREAD

**Issue by CryptoJackIRL** [nazar-pc/space-acres#56] opened 2023-12-20 01:00 UTC
App crashes will following event log info:

Faulting application name: space-acres.exe, version: 0.0.8.0, time stamp: 0x6580ae2d
Faulting module name: VCRUNTIME140.dll, version: 14.38.33130.0, time stamp: 0x97a23cdb

**Comment by CryptoJackIRL** [comment] 2023-12-20 01:09
Also, found this in the System event log:

Windows successfully diagnosed a low virtual memory condition. The following programs consumed the most virtual memory: space-acres.exe (11628) consumed 21093511168 bytes

Looks like there's a memory leak.

**Comment by nazar-pc** [comment] 2023-12-20 01:10
How much RAM does the machine have in total?

**Comment by CryptoJackIRL** [comment] 2023-12-20 01:11
Also, for reference, my system specs:
CPU - E5-2699 v4 2.2GHZ
RAM - 16GB
SSD - 128GB

**Comment by nazar-pc** [comment] 2023-12-20 01:12
Any page file at all? Is there anything else running on this machine?

"consumed 21093511168" is less than 20GB, which for virtual memory isn't a lot at all.

**Comment by CryptoJackIRL** [comment] 2023-12-20 01:13
The page file is system managed and currently at 3.7GB.  I may need to set it to manual and set it higher?

**Comment by nazar-pc** [comment] 2023-12-20 01:20
Is there anything else running on that machine besides Space Acres?

**Comment by CryptoJackIRL** [comment] 2023-12-20 01:21
No. I have separate installations for each node i run.

**Comment by nazar-pc** [comment] 2023-12-20 01:22
Yeah, looks like you'll want to increase that according to quick search online.
This article has screenshots: https://www.enjoysharepoint.com/windows-successfully-diagnosed-a-low-virtual-memory-condition-error/

**Comment by CryptoJackIRL** [comment] 2023-12-20 01:28
I used Microsoft recommendation of RAM(16GB) * 1.5 for initial and x3 for maximum.  Page file currently sitting at 25GB.
I'll update if rest of sync is successful.

Thanks for the help.

**Comment by nazar-pc** [comment] 2023-12-20 01:42
Let me close this for now then, we can reopen if it is still an issue

**Comment by CryptoJackIRL** [comment] 2023-12-20 15:17
It was crashed this morning with this error in the System event log:

Windows successfully diagnosed a low virtual memory condition. The following programs consumed the most virtual memory: space-acres.exe (9468) consumed 91717292032 bytes

That's a lot of virtual memory.

**Comment by nazar-pc** [comment] 2023-12-20 15:20
It is virtual memory, not physical, applications like browsers use a huge amounts of it.

Have you used CLI farmer (reference implementation or Pulsar) in the past? If so, did you have similar issues with those?

**Comment by CryptoJackIRL** [comment] 2023-12-20 15:30
I've only used Space Acres so far.

**Comment by nazar-pc** [comment] 2023-12-20 15:38
Can you run the app and see if it uses more RAM over time according to Task Manager without you doing anything with it?

**Comment by nazar-pc** [comment] 2023-12-20 15:40
I've created upstream GTK4 issue: https://gitlab.gnome.org/GNOME/gtk/-/issues/6285

Will look into how to work around this.

**Comment by CryptoJackIRL** [comment] 2023-12-20 16:00
I've setup Windows performance monitor, but it won't record data for very long, only a few hours.  I'll see if I get something from that.

**Comment by nazar-pc** [comment] 2023-12-20 16:25
Thanks! Appreciate all the details so far, we'll try to figure out what is going on, but need to isolate it a bit more first.

**Comment by CryptoJackIRL** [comment] 2023-12-20 20:27
The virtual memory usage for Space-Acres is sitting at about 27GB.  My page file is 55GB.  

Looking at performance monitor logs for the last 3 hours, it looks like Space-Acres increases virtual mem usage at about around 2GB per hour.

**Comment by nazar-pc** [comment] 2023-12-20 20:31
What about residential memory?

**Comment by CryptoJackIRL** [comment] 2023-12-20 20:32
> What about residential memory?

Not sure what you mean by that.

**Comment by nazar-pc** [comment] 2023-12-20 20:33
It is more "normal" memory that is typically shown in task manager for example

**Comment by CryptoJackIRL** [comment] 2023-12-20 20:34
Ah.  Not much.  Although that slowly increases as well, it's by very small amount.  It's only using just over 1GB Ram right now.

**Comment by nazar-pc** [comment] 2023-12-20 20:58
Is this a physical machine or a VM BTW? 16G of RAM is too little for such a machine.

**Comment by CryptoJackIRL** [comment] 2023-12-20 21:01
It's a VM.   What do you recommend for ram?   Also, there doesn't seem to be an issue with RAM usage.
I still have 5GB of RAM free.

**Comment by nazar-pc** [comment] 2023-12-20 21:03
RAM is fine, I was just suspecting it is a VM since you have so little RAM and so many cores.
GPU drivers in VMs are typically not supporting all the features, which may lead to using suboptimal paths that will leak memory that are not reproducible on physical hardware with proper GPU and hardware acceleration.

If it is a VM dedicated to Subspace anyway (at least that is how I interpret it), I'd recommend trying to use Ubuntu in a VM instead, there is a chance it will work better.

**Comment by CryptoJackIRL** [comment] 2023-12-20 21:04
I can use space acres with Ubuntu?

**Comment by nazar-pc** [comment] 2023-12-20 21:05
Yes, recent releases did add Ubuntu 22.04+ support (earlier versions didn't have Ubuntu support unless you compile it from scratch, which is not that difficult on Ubuntu).

**Comment by CryptoJackIRL** [comment] 2023-12-20 21:06
Is the Ubuntu version a CLI version?

**Comment by nazar-pc** [comment] 2023-12-20 21:07
Nope, it is identical graphical application

**Comment by CryptoJackIRL** [comment] 2023-12-20 21:09
It's almost done syncing now.  After it's done syncing, gonna restart the app, which should clear out the virtual mem usage, then see how it runs once syncing is complete.

**Comment by CryptoJackIRL** [comment] 2023-12-20 23:56
Just a quick update.   Sync completed.   Afterwards, i set the windows virtual mem management back to auto and rebooted.  The initial plotting is being done now and there doesn't seem to be any issue with virtual mem usage.   I'll update when initial plotting is complete.

**Comment by CryptoJackIRL** [comment] 2023-12-26 15:46
During plotting, I still see large growth in Virtual Memory.   I shutdown the PC, increased the RAM to 96GB, and started space acres back up.  It's been running for a day or so, and the space-acres process is using 3.8GB RAM, but it's appears to be using 47.8GB RAM for caching.  My Task Manager performance tab shows 47.8GB Cached .

**Comment by CryptoJackIRL** [comment] 2023-12-27 01:56
At 85% plotting now and things seem to have stabilized.  RAM cached still sitting around 48GB.  About 5GB of Virtual Mem used.  Looks like a lot of RAM is necessary.  Could probably have gotten away with just 64GB.  Not sure if more RAM would be needed for more than 1TB plot.

**Comment by nazar-pc** [comment] 2023-12-27 01:58
> RAM cached still sitting around 48GB

Cache is up to OS, it can be freed any time and not something you should be worried about.

> Looks like a lot of RAM is necessary

No, a lot of RAM is not necessary. This issue is a bug and it will be fixed at some point. The fact that memory is leaking right now doesn't mean a lot of RAM is necessary.

**Comment by nazar-pc** [comment] 2024-01-01 16:04
I think the root cause of this might have been fixed in GTK's `main` here: https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/6688
And is being backported into the next stable release here: https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/6697

Once new stable release is out, we'll upgrade to it and the issue will hopefully be gone.

**Comment by nazar-pc** [comment] 2024-01-04 22:42
While GTK was leaking memory for sure, I think the root cause is ParityDb, here is an upstream issue about this: https://github.com/paritytech/parity-db/issues/233

**Closed** 2024-01-05 15:56 UTC
Labels: bug, Windows
